apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ptp-app-stage
  namespace: openshift-ptp
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - ptp-app-stage
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ptp-subscription-stage
  namespace: openshift-ptp
  labels:
    app: ptp-app-stage
  annotations:
    apps.open-cluster-management.io/git-path: operator/ptp
    apps.open-cluster-management.io/git-branch: stage
spec:
  name: ptp-subscription-stage
  channel: openshift-ptp/ptp-channel-github
  placement:
    placementRef:
      kind: PlacementRule
      name: stage-clusters
