apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: performance-addon
  namespace: openshift-performance-addon
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      performance: "true"
