apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sctp
  namespace: acm-cnf-sctp
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      sctp: "true"
