apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: upgrade-mcp-cnf22-app
  namespace: default 
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - upgrade-mcp-cnf22-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: upgrade-mcp-subscription-cnf22
  namespace: default
  labels:
    app: upgrade-mcp-cnf22-app
  annotations:
    apps.open-cluster-management.io/git-path: cnf22 
    apps.open-cluster-management.io/git-branch: cnf22
spec:
  name: upgrade-mcp-subscription-cnf22
  channel: default/acm-cnf
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-hub
