apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  additionalKernelArgs:
  - nmi_watchdog=0
  - audit=0
  - mce=off
  - processor.max_cstate=1
  - idle=poll
  - intel_idle.max_cstate=0
  - nosmt
  - tsc=reliable
  cpu:
    isolated: 5-30
    reserved: 0-4
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 8 
      size: 1G
      node: 0
    - count: 8 
      size: 1G
      node: 1 
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  numa:
    topologyPolicy: best-effort
  realTimeKernel:
    enabled: true
