apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: sctp-channel-github
  namespace: openshift-sctp
spec:
  type: Git
  pathname: https://github.com/alosadagrande/acm-cnf.git
