apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: stage-clusters 
  namespace: sctp-gitops 
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchLabels:
      environment: "stage"
