apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: upgrade-mcp-cnf22-app
  namespace: openshift-performance-addon-operator
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - upgrade-mcp-cnf22-app
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: upgrade-mcp-subscription-cnf22
  namespace: openshift-performance-addon-operator
  labels:
    app: upgrade-mcp-cnf22-app
  annotations:
    apps.open-cluster-management.io/git-path: policies-and-misc/update-same-cluster
    apps.open-cluster-management.io/git-branch: master 
spec:
  name: upgrade-mcp-subscription-cnf22
  channel: openshift-performance-addon-operator/pao-channel-github
  placement:
    placementRef:
      kind: PlacementRule
      name: placement-upgrade-mcp 
