apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-ptp
  namespace: openshift-ptp
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      ptp: "true"
