apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ptp-placement
  namespace: openshift-ptp
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: "cnf10"
