apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  cpu:
    isolated: "8-31"
    reserved: "0-7"
  hugepages:
    defaultHugepagesSize: "1G"
  realTimeKernel:
    enabled: false
  numa:
    topologyPolicy: "best-effort"
