apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: performance-addon-cnf20
  namespace: openshift-performance-addon
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      cluster: "cnf20"
