apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sriov-placement
  namespace: cnf-operators
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchLabels:
      sriov: true
