apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sctp-placement
  namespace: cnf-operators
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions: 
      - {key: sctp, operator: In, values: ["true"]}
