apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: grandmaster
spec:
  profile:
  - interface: eno1
    name: grandmaster
    phc2sysOpts: '-a -r -r'
    ptp4lOpts: ''
  recommend:
  - match:
      nodeLabel: 'node-role.kubernetes.io/worker-cnf'
    - nodeName: 'cnf10-master-0.cnf10.kni.lab.eng.bos.redhat.com'
    priority: 4
    profile: grandmaster
