apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: grandmaster
spec:
  profile:
  - interface: eno1
    name: grandmaster
    phc2sysOpts: '-a -r -r'
    ptp4lOpts: ''
  recommend:
  - match:
    - nodeName: 'cnf10-worker-0.dev5.kni.lab.eng.bos.redhat.com'
    priority: 4
    profile: grandmaster
