apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    release.openshift.io/version: ""
  name: linuxptp-daemon
  namespace: openshift-ptp
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: linuxptp-daemon
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linuxptp-daemon
    spec:
      containers:
      - args:
        - /usr/local/bin/ptp --alsologtostderr -v 10
        command:
        - /bin/bash
        - -c
        - --
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: registry.redhat.io/openshift4/ose-ptp@sha256:284dbeac3793b5b619fa073e229da4e46a1ef70daaa1a4958d085beb6898db3d
        imagePullPolicy: IfNotPresent
        name: linuxptp-daemon-container
        ports:
        - containerPort: 9091
          hostPort: 9091
          name: metrics-port
          protocol: TCP
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/linuxptp
          name: config-volume
      dnsPolicy: ClusterFirst
      hostNetwork: true
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/worker-cnf: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: linuxptp-daemon
      serviceAccountName: linuxptp-daemon
      terminationGracePeriodSeconds: 30
      tolerations:
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: ptp-configmap
        name: config-volume
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
