apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: cluster-cnf10 
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchLabels:
      name: cnf10
