apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-node
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-worker-nodes
        spec:
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Node
                metadata:
                  labels:
                    beta.kubernetes.io/arch: amd64
          remediationAction: inform
          severity: low
  remediationAction: inform 
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-node
placementRef:
  name: placement-policy-pao
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-node
  kind: Policy
  apiGroup: policy.open-cluster-management.io
