apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: sriov-app-stage
  namespace: openshift-sriov-network-operator
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - sriov-app-stage
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: sriov-subscription-operator
  namespace: openshift-sriov-network-operator
  labels:
    app: sriov-app-stage
  annotations:
    apps.open-cluster-management.io/git-path: operator/sriov
    apps.open-cluster-management.io/git-branch: stage
spec:
  name: sriov-subscription-operator
  channel: openshift-sriov-network-operator/sriov-channel-github
  placement:
    placementRef:
      kind: PlacementRule
      name: stage-clusters
