apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: stage-clusters
  namespace: openshift-performance-addon
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      env: "stage"
