apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  cpu:
    isolated: "10-31"
    reserved: "0-2"
  hugepages:
    defaultHugepagesSize: "1G"
    pages:
    - size: "1G"
      count: 8
  realTimeKernel:
    enabled: true
