apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#bases:
#  - 'github.com/alosadagrande/acm-cnf/operator/dpdk/?ref=config'

#patchesStrategicMerge:
resources:
  - deployment-testpmd.yaml 
