apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: klusterlets.operator.open-cluster-management.io
spec:
  conversion:
    strategy: None
  group: operator.open-cluster-management.io
  names:
    kind: Klusterlet
    listKind: KlusterletList
    plural: klusterlets
    singular: klusterlet
  scope: Cluster
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Klusterlet represents controllers on the managed cluster. When
          configured, the Klusterlet requires a secret named of bootstrap-hub-kubeconfig
          in the same namespace to allow API requests to the hub for the registration
          protocol.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec represents the desired deployment configuration of Klusterlet
              agent.
            properties:
              clusterName:
                description: ClusterName is the name of the managed cluster to be
                  created on hub. The Klusterlet agent generates a random name if
                  it is not set, or discovers the appropriate cluster name on openshift.
                type: string
              externalServerURLs:
                description: ExternalServerURLs represents the a list of apiserver
                  urls and ca bundles that is accessible externally If it is set empty,
                  managed cluster has no externally accessible url that hub cluster
                  can visit.
                items:
                  description: ServerURL represents the apiserver url and ca bundle
                    that is accessible externally
                  properties:
                    caBundle:
                      description: CABundle is the ca bundle to connect to apiserver
                        of the managed cluster. System certs are used if it is not
                        set.
                      format: byte
                      type: string
                    url:
                      description: URL is the url of apiserver endpoint of the managed
                        cluster.
                      type: string
                  type: object
                type: array
              namespace:
                description: Namespace is the namespace to deploy the agent. The namespace
                  must have a prefix of "open-cluster-management-", and if it is not
                  set, the namespace of "open-cluster-management-agent" is used to
                  deploy agent.
                type: string
              registrationImagePullSpec:
                description: RegistrationImagePullSpec represents the desired image
                  configuration of registration agent.
                type: string
              workImagePullSpec:
                description: WorkImagePullSpec represents the desired image configuration
                  of work agent.
                type: string
            type: object
          status:
            description: Status represents the current status of Klusterlet agent.
            properties:
              conditions:
                description: 'Conditions contain the different condition statuses
                  for this Klusterlet. Valid condition types are: Applied: components
                  have been applied in the managed cluster. Available: components
                  in the managed cluster are available and ready to serve. Progressing:
                  components in the managed cluster are in a transitioning state.
                  Degraded: components in the managed cluster do not match the desired
                  configuration and only provide degraded service.'
                items:
                  description: StatusCondition contains condition information.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the last time the condition
                        changed from one status to another.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human-readable message indicating
                        details about the last status change.
                      type: string
                    reason:
                      description: Reason is a (brief) reason for the condition's
                        last status change.
                      type: string
                    status:
                      description: Status is the status of the condition. One of True,
                        False, Unknown.
                      type: string
                    type:
                      description: Type is the type of the cluster condition.
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
