namespace: openshift-ptp
commonLabels:
  app: acm-alo-ptp
bases:
- ./../base
patchesStrategicMerge:
- overlays/namespace.yaml
resources:
- overlays/ptpconfig-grandmaster.yaml
- overlays/ptpconfig-slave.yaml


