apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ptp-app-cnf10
  namespace: openshift-ptp
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - ptp-app-cnf10
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ptp-subscription-cnf10
  namespace: openshift-ptp
  labels:
    app: ptp-app-cnf10
  annotations:
    apps.open-cluster-management.io/github-path: operator/ptp/
    apps.open-cluster-management.io/github-branch: cnf10
spec:
  name: ptp-subscription-cnf10
  channel: openshift-ptp/ptp-channel-github
  placement:
    placementRef:
      kind: PlacementRule
      name: ptp-placement-cnf10
