apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ptp-placement-cnf10
  namespace: openshift-ptp
spec:
  clusterConditions:
  - type: ManagedClusterConditionAvailable
    status: "True"
  clusterSelector:
    matchLabels:
      cluster: "cnf10"
